### ISSUE TITLE
Would I be able to directly use it in app.config?

### ISSUE THREAD

**Issue by jremya** [urish/angular-load#11]

**Comment by jremya** [comment]
We have a single module and we are in need of the the dynamic script to be loaded before the $stateProviders are invoked.  We tried injecting as below, 

.config(function( $stateProvider, $urlRouterProvider,  $httpProvider, angularLoad ) {

But got an error mentioning angularLoad is not a valid Provider.

**Comment by urish** [comment]
Right, this is not possible with angularLoad, as angularLoad loads the script asynchronously. The best way to go about this is probably to load the script dynamically (using require.js or similar) and bootstrap AngularJS manually only after the script has been loaded.
