### ISSUE TITLE
Implement cross-compatibility testing by means of SauceLabs

### ISSUE THREAD

**Issue by evilaliv3** [urish/angular-load#13]
While working on [GlobaLeaks](https://github.com/globaleaks/GlobaLeaks), we found out that It would be valuable to implement an integration with [SauceLabs](https://saucelabs.com/) in order to perform end-to-end testing in the cloud testing against cross-browser compatibility.

Given the fact that angular-load is using Grunt, this would be really simple by using [grunt-protractor-runner](https://github.com/teerapap/grunt-protractor-runner)

**Comment by urish** [comment]
@evilaliv3 you are invited to send a PR with the proposed changes.
