### ISSUE TITLE
ReferenceError: angularLoad is not defined

### ISSUE THREAD

**Issue by RafaelPlantard** [urish/angular-load#14]
The angular-load is set up correct, but I am receiving those error messages.

![image](https://cloud.githubusercontent.com/assets/5968478/7714219/4963f6ce-fe53-11e4-9bfb-6202121fbf90.png)

![image](https://cloud.githubusercontent.com/assets/5968478/7714217/4326ae1e-fe53-11e4-90cc-c47e72f4e1e8.png)

![image](https://cloud.githubusercontent.com/assets/5968478/7714197/13a9c414-fe53-11e4-97a1-60805df0c7e8.png)

**Comment by RafaelPlantard** [comment]
My bad...

**Comment by Arcrammer** [comment]
What was the problem? I'm running into the same issue.

**Comment by RafaelPlantard** [comment]
I'm sorry @Arcrammer but I don't remember.

**Comment by Arcrammer** [comment]
Thanks!
