### ISSUE TITLE
IE8 compatibility

### ISSUE THREAD

**Issue by arambert** [urish/angular-load#17]
To ensure IE 8 compatibility, one must change the line https://github.com/urish/angular-load/blob/master/angular-load.js#L61 by : 

    var ua = $window.navigator.userAgent.toLowerCase();
    if (ua.indexOf('msie 8') != -1){
      document.getElementsByTagName('head')[0].appendChild(style);
    } else {
      $document[0].head.appendChild(style);
    }

I hope it will help !

**Comment by urish** [comment]
thanks, though, I am not interested in maintaining IE8 compatibility
