### ISSUE TITLE
Incompatible with Angular 1.6.0

### ISSUE THREAD

**Issue by jeraldrich** [urish/angular-load#38]
When updating angular to 1.6.0, angular-load does not have a compatible version. 

Here is the angular 1.6.0 changelog: https://github.com/angular/angular.js/blob/master/CHANGELOG.md

**Comment by irfanka** [comment]
What exactly isn't working with 1.6.0?

**Comment by jeraldrich** [comment]
@irfanka The angular dependency locks the angular version to anything less than 1.6.0 https://github.com/urish/angular-load/blob/master/bower.json#L9

I tested angular-load using angular 1.6.3, everything is working fine.

**Comment by asciutto990** [comment]
I just tested this with 1.6.4 and it worked fine there as well.
