### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by urish** [urish/angular-load#39]
This project needs some love, and I can no longer find the time required to maintain it. If anybody wants to stand up as a new maintainer, please comment here. Thanks!

**Comment by Attrash-Islam** [comment]
:sunglasses: :laughing:

**Comment by urish** [comment]
Thanks again for all you have been doing for [angular-spinner](https://github.com/urish/angular-spinner) 👍

**Comment by Attrash-Islam** [comment]
To give a try here in the next two weeks with webpack and TypeScript?

**Comment by cseale** [comment]
Submitted a PR there. I will be happy to take this on!

**Comment by urish** [comment]
Thank you @cseale ! 

I am adding you as a collaborator to this repo, so you can work on your pull request and merge it when you feel it is ready. If you need any guidance, feel free to tag me or Islam (who did a similar process with angular-spinner) with any questions.

Once you have a version ready to upload to NPM, ping me and we'll do this together.
