### ISSUE TITLE
Release 0.4.2

### ISSUE THREAD

**Issue by rsaintcyr-creditshop** [urish/angular-load#41]
Is there a planned release for 0.4.2? I'd like to use unloadCSS but it's not available in 0.4.1, the last release available on github and bower.

**Comment by cseale** [comment]
Hi @rsaintcyr-creditshop. I just recently started helping to maintain this repo. I wasn't aware the current release was missing the `unloadCSS` functionality! I will do a release of `0.5.0` later today/tomorrow, and you can verify it works for you

**Comment by rsaintcyr-creditshop** [comment]
Thanks @cseale that would be great, I'll be happy to verify the release when it's ready.

**Comment by cseale** [comment]
try now, version 0.5.0

**Comment by rsaintcyr-creditshop** [comment]
Git still reports 0.4.1 as latest release. 
From "bower info angular-load" :
`Available versions:
  - 0.4.1
  - 0.4.0
  - 0.3.0
  - 0.2.0
  - 0.1.2
  - 0.1.1
  - 0.1.0
`

**Comment by cseale** [comment]
@rsaintcyr-creditshop I published the npm package, but didn't publish to the bower registry. Will do that in the next few hours after work. Sorry!

**Comment by cseale** [comment]
@rsaintcyr-creditshop ok should be published correctly now to npm and bower, `0.5.0`

**Comment by rsaintcyr-creditshop** [comment]
Works great, thanks for the response.
