### ISSUE TITLE
Not compatible with Angular 1.6.4

### ISSUE THREAD

**Issue by ykeysergit** [urish/angular-load#42]
Got error when installing via bower. I think the error is caused by:

  dependencies: {
    angular: '>=1.0.0 <1.6.0'

Could you please confirm?

**Comment by cseale** [comment]
It should be 1.7.0. It is compatible and testing with 1.6.X

https://github.com/urish/angular-load/blob/master/package.json#L10

if you want you can submit a PR to fix this?

**Comment by ykeysergit** [comment]
Closed due to low priority
